image: node:latest

# Cache modules in between jobs
# https://docs.gitlab.com/ee/ci/caching/#cache-nodejs-dependencies
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

workflow:
  # Run this workflow when a tag is pushed
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: $CI_COMMIT_TAG

variables:
  RELEASE_DOWNLOAD: "https://gitlab.com/$CI_PROJECT_PATH/-/jobs/artifacts/$CI_COMMIT_TAG/raw/dnd5e.zip?job=deploy"

# 1. Test if the version matches the tag and exit if not
test-version:
  stage: .pre
  script:
    # Extract version from system.json
    - PACKAGE_VERSION=$(node -p "require('./system.json').version")
    - PACKAGE_DOWNLOAD=$(node -p "require('./system.json').download")

    # Validate that the tag being released matches the package version.
    - |
      if [[ ! $CI_COMMIT_TAG =~ /^release-$PACKAGE_VERSION/ ]]; then
        echo "The system.json version does not match tag name."
        echo "system.json: $PACKAGE_VERSION"
        echo "tag name: $CI_COMMIT_TAG"
        echo "Please fix this and push the tag again."
        exit 1
      fi
    # Validate that the package download url matches the release asset that will be created.
    - |
      if [[ ! $RELEASE_DOWNLOAD == $PACKAGE_DOWNLOAD ]]; then
        echo "The system.json download url does not match the created release asset url."
        echo "system.json: $PACKAGE_DOWNLOAD"
        echo "release asset url: $RELEASE_DOWNLOAD"
        echo "Please fix this and push the tag again."
        exit 1
      fi

# 2. Install NPM dependencies, build, compile the zip.
build:
  stage: build
  script:
    # Use cached npm
    - npm ci --cache .npm --prefer-offline
    # Run build script
    - npm run build
    # zip whitelist of files to distribute
    - zip dnd5e.zip -r icons lang module packs/*.db templates tokens ui dnd5e.css dnd5e.js LICENSE.txt OGL.txt README.md system.json template.json

# 3. Attach build artifacts as release assets
# https://docs.gitlab.com/ee/ci/yaml/index.html#complete-example-for-release
release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  artifacts:
    # include the system json and created zip file as artifacts of the job
    paths:
      - dnd5e.zip
      - system.json
    expire_in: never
  release:
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'system.json'
          url: 'https://gitlab.com/$CI_PROJECT_PATH/-/jobs/artifacts/$CI_COMMIT_TAG/raw/system.json?job=deploy'
          filepath: '/system.json' # optional
        - name: 'dnd5e.zip'
          url: $RELEASE_DOWNLOAD
          filepath: '/dnd5e.zip' # optional
